spring:
  datasource:
    name: mediapp
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL

  http:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

file-manager:
  base-folder:  /home/ec2-user/data
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}.%M-%line - %msg%n"
server:
  port: 8080
